### PR TITLE
build(go): upgrade to v1.22.0

### PR DESCRIPTION
**Pull request by 1602077**
* build(go): upgrade to latest stable version of go (1.22.0).
* build(go): upgrade all library dependencies to latest versions.
* chore(go): formatted codebase with `gofumpt`.

### CODE REVIEW

**Review by Ankurk99 — APPROVED** [review]
LGTM!

**Comment by Ankurk99** [comment]
@1602077 Just to confirm, did you also test these changes locally?

**Comment by 1602077** [comment]
> @1602077 Just to confirm, did you also test these changes locally?

@Ankurk99 Yep followed a similar procedure to that described in cvmfs-csi to run this is a fresh cluster. Also ran the functional integration tests in the k8s gitlab

**Review by rochaporto — APPROVED** [review]
LGTM

**Pull request merged**
